### ISSUE TITLE
How to use orz with tar?

### ISSUE THREAD

**Issue by Windforce17** [richox/orz#25]
tar has an argument`--use-compress-program` , but I don't know how to use with orz.

**Comment by richox** [comment]
i think it's because orz command line options is not compatible with compress (like `gzip <in >out.gz` for compression and `gzip -d <in.gz >out` for decompression). anyway you can first create an uncompressed tar file with `tar -cf xxx.tar ./xxx` then run `orz encode <xxx.tar >xxx.tar.orz` to compress it.

another way is making the command line options (structopt) compatible with compress. but i currently have no time on it. any PR is welcome.
